### ISSUE TITLE
ClingoLP installation problems

### ISSUE THREAD

**Issue by daveraja** [potassco/conda#15] opened 2020-06-17 01:44 UTC
When I try to install clingo-lp from conda it fails and reports a conflict. I have tried this from a completely clean conda environment:

`$ conda create -n tmpenv python=3.7`
`$ conda activate tmpenv`
`$ conda install -c conda-forge lpsolve55`
`$ conda install -c potassco clingo clingo-lp`

This returns the error:

> Collecting package metadata (current_repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.
Collecting package metadata (repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: / 
Found conflicts! Looking for incompatible packages.
This can take several minutes.  Press CTRL-C to abort.
failed                                                                                                                  
>
>UnsatisfiableError: The following specifications were found to be incompatible with each other:
>
>Output in format: Requested package -> Available versions
>
>Package _libgcc_mutex conflicts for:
python=3.7 -> libgcc-ng[version='>=7.3.0'] -> _libgcc_mutex=[build=main]
clingo -> libgcc-ng[version='>=7.3.0'] -> _libgcc_mutex=[build=main]
>
>Package clingo conflicts for:
clingo-lp -> clingo[version='>=5.4.0']
clingo

I also tried other combinations: installing clingo and clingo-lp separately, installing the dev clingo then clingo-lp. All have failed.

But removing the `lpsolve55` requirement in `run` seems to fix the problem. I was able to build and upload to my [personal anaconda package](https://anaconda.org/daveraja/clingo-lp) and install from there.

However, I can't make out what the underlying problem is. The above error suggests a conflict between clingo and clingo-lp. But without the lpsolve55 requirement there is no conflict. But lpsolve55 and clingo-lp don't conflict either since I can actually install them both independently and it works fine.

**Comment by rkaminsk** [comment] 2020-06-17 09:53
You could use an environment with python 3.6 for the moment. I can reproduce the error but don't get any helpful error messages.

```
$ conda install  -c conda-forge -c potassco clingo-lp
Collecting package metadata (current_repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.
Collecting package metadata (repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: - 
Found conflicts! Looking for incompatible packages.
This can take several minutes.  Press CTRL-C to abort.
failed                                                                                                                                                                             

UnsatisfiableError: The following specifications were found to be incompatible with each other:

Output in format: Requested package -> Available versions
```

**Comment by rkaminsk** [comment] 2020-06-17 11:12
I do not understand what is happening but I simply removed python from the build and run requirements of the package and now it installs with python 3.7 too.

**Comment by daveraja** [comment] 2020-06-17 11:14
Cool thanks. Strange conda stuff. I'm not entirely sure why I didn't try python 3.6 in the first place  ;)

**Comment by rkaminsk** [comment] 2020-06-18 09:46
Since it is somehow working now, I am closing this. It would still be nice to know about the why...

**Closed as completed by rkaminsk** 2020-06-18 09:46 UTC
